# Generated by Django 4.1 on 2022-09-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('usd_price', models.FloatField()),
                ('rub_price', models.FloatField()),
                ('delivery_time', models.DateField()),
                ('notify', models.BooleanField(default=False)),
            ],
        ),
    ]
