# Generated by Django 4.1 on 2022-09-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheet',
            name='usd_price',
            field=models.IntegerField(),
        ),
    ]
